services:
  - type: web
    name: musicsync
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: SERVER_PORT
        value: "8080"
    healthCheckPath: /
    autoDeploy: true
